services:
  ds-database:
    container_name: ds-database
    image: postgres:17.6
    environment:
      POSTGRES_DB: "directory_service"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fs-database:
    container_name: fs-database
    image: postgres:17.6
    environment:
      POSTGRES_DB: "file_service"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - fs_postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - fs-database
      - ds-database
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
  seq:
    container_name: seq
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data
  tm-loki:
    container_name: tm-loki
    image: grafana/loki:3.4.1
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml:ro
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
  tm-prometheus:
    image: prom/prometheus:v3.7.2
    container_name: tm-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    expose:
      - 9090
  tm-promtail:
    image: grafana/promtail:2.9.0
    container_name: tm-promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
  tm-grafana:
    container_name: tm-grafana
    image: grafana/grafana
    ports:
      - '3002:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
  ds-api:
    build:
      context: ./DirectoryService
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: ds-api
    ports:
      - "5000:8080"
    depends_on:
      - ds-database
      - seq
      - redis
    env_file:
      - ds.env
  fs-api:
    build:
      context: ./FileService
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}  
    container_name: fs-api
    ports:
      - "5001:8080"
    depends_on:
      - seq
      - minio
      - fs-database
    env_file:
      - fs.env

volumes:
  postgres_data:
  seq-data:
  redis_data:
  minio_data:
  grafana-storage:
  prometheus_data:
  grafana-data:
  fs_postgres_data: